<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Sales King Academy</title>
  <style>
    body {margin: 0; font-family: sans-serif; background: #f9f9f9; color: #333;}
    header {background: #000; color: #fff; padding: 2rem; text-align: center;}
    header h1 {margin: 0; font-size: 2.5rem;}
    header p {margin: 0.5rem 0 0;}
    section {padding: 2rem; text-align: center;}
    section h2 {font-size: 1.75rem; margin-bottom: 1rem;}
    section p {max-width: 600px; margin: 0 auto 1.5rem;}
    button {background: #d72638; color: #fff; border: none; padding: 1rem 2rem; font-size: 1rem; cursor: pointer; border-radius: 5px;}
    button:hover {background: #c21f31;}
    .features {display: flex; flex-direction: column; gap: 1rem; max-width: 600px; margin: 2rem auto;}
    .features div {background: #fff; padding: 1rem; border: 1px solid #ddd; border-radius: 8px;}
    .testimonials {background: #f1f1f1; padding: 2rem;}
    .testimonial {margin: 1rem auto; max-width: 600px; font-style: italic;}
    .footer {background: #000; color: #fff; padding: 1rem; text-align: center; font-size: 0.9rem; margin-top: 2rem;}
    input[type="text"], input[type="email"] {padding: 0.5rem; margin: 0.5rem; width: 40%;}
    form {margin-top: 1rem;}
  </style>
</head>
<body>
  <header>
    <h1>Sales King Academy</h1>
    <p>Dominate Your Sales Game with Proven Strategies</p>
  </header>

  <section>
    <h2>Ready to Close Bigger?</h2>
    <p>Accelerate deals, learn from top experts, and build your sales empire with our comprehensive training.</p>
    <button onclick="alert('Thank you! We\'ll reach out soon.')">Get The Free Intro</button>
  </section>

  <section class="features">
    <div><strong>✔ Proven Sales Framework</strong></div>
    <div><strong>✔ Expert-Led Training</strong></div>
    <div><strong>✔ Supportive Community</strong></div>
  </section>

  <section class="testimonials">
    <h2>What Our Students Say</h2>
    <div class="testimonial">"I tripled my closing rate in just 30 days. Sales King Academy is the real deal!" – Jordan M.</div>
  </section>

  <section>
    <h2>Join Now</h2>
    <p>Enter your name and email and we’ll get you started today.</p>
    <form onsubmit="event.preventDefault(); alert('Thanks for signing up!')">
      <input type="text" placeholder="Your Name" required />
      <input type="email" placeholder="Your Email" required />
      <button type="submit">Reserve My Spot</button>
    </form>
  </section>

  <div class="footer">
    &copy; 2025 Sales King Academy. All rights reserved.
  </div>
</body>
</html>
services:
  - type: web
    name: sales-king-academy
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
